### ISSUE TITLE
Project TODO List

### ISSUE THREAD

**Issue by Aboshxm2** [Aboshxm2/tuwaiq-php-laravel#2]
### Features
- [ ] Localization
- [ ] Validation Rules
- handle validation errors
- [ ] Implement Product Tags
- [ ] Implement Reviews
- [ ] Change Dashboard System
- haven't planned well for this but the current system is disgusting
- consider implementing an editing system for product images/variants as part of the product
- [ ] Implement Proper Search System
- proper search system that includes searching via groups, categories, tags...
- [ ] Implement Footer Pages (About Us, Support, Contact Us, TOS)
- [ ] Implement a Way to Edit the Products on the Home Page

### Bugs
- [ ] Calculating the Total While Changing the Product Quantity

### Design
- [ ] Text Fonts
- [ ] Page Icon + Title
- [ ] Improve Design
- make a use of components 
- split large blade files into parts
- [ ] Remove All Database Usage in blade files
- simply this is security threat and dirty design

### Refactor
- [ ] Refactor Categories 
- refactoring categories to be shareable across groups to avoid redundancy. For example, instead of having one category "Shoes" for Men group and another "Shoes" category for Women, it would be better to create a single category "Shoes" and assign that category to Men and Women groups
- [ ] Simplify Controllers

### Other
- [ ] License
- [ ] PHP CS Fixer
- [ ] Upload The Project Online
